version: '3.1'

services:
  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "mypguser"
      POSTGRES_DB: "mydb"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/"
      - "./postgres:/docker-entrypoint-initdb.d/"
      
  app:
    build: ./src
    ports:
      - "8080:8080"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080