BEGIN;

CREATE TABLE notes(
	id SERIAL NOT NULL PRIMARY KEY,
	text VARCHAR(1000),
	createdOn TIMESTAMP NOT NULL DEFAULT now(),
	updatedOn TIMESTAMP NOT NULL DEFAULT now()
); 

CREATE TABLE users(
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(128) NOT NULL UNIQUE,
	password VARCHAR(1024) NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT now(),
	updatedOn TIMESTAMP NOT NULL DEFAULT now()
); 

COMMIT;
