BEGIN;

CREATE TABLE users(
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(128) NOT NULL UNIQUE,
	password VARCHAR(1024) NOT NULL,
	createdon TIMESTAMP NOT NULL DEFAULT now(),
	updatedon TIMESTAMP NOT NULL DEFAULT now()
); 

CREATE TABLE notes(
	id SERIAL NOT NULL PRIMARY KEY,
	text VARCHAR(1000),
	userid Integer NOT NULL,
	createdon TIMESTAMP NOT NULL DEFAULT now(),
	updatedon TIMESTAMP NOT NULL DEFAULT now()
); 

COMMIT;
